[package]
name = "misc"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "misc"

[dependencies]
hdk = { workspace = true }

serde = { workspace = true }

utils = { workspace = true }
 
