[package]
name = "profiles_integrity"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "profiles_integrity"

[dependencies]

hdi = { workspace = true }

serde = { workspace = true }

chrono = { workspace = true }

image = { workspace = true }
